// import React, { CSSProperties } from 'react';
import { CustomRootComponentConfig, RenderProps } from '@typings/puck';
// import { UnitFieldValue } from '@typings/fields';
import { properties, sharedCss } from '../../../../css-variables';
import { DefaultComponentProps } from '@measured/puck';
import { Typography } from '../Typography';
import { UnitFieldValue } from '@typings/fields';
// import { processPropsWithInternalFields } from '../createPuckComponent';

const defaultBackground = new URL('./default-background.jpg', import.meta.url).href;

export interface InternalFieldsBackgroundProps {
  $appearance: {
    design: {
      /** Optional image filters */
      useAdvancedFilters: boolean;
      filterBlur: number;
      filterBrightness: number;
      filterContrast: number;
      filterSaturate: number;
      filterGrayscale: number;
    };
    spacing: {
      margin: UnitFieldValue;
      padding: UnitFieldValue;
    };
  };
}

export const defaultRootConfig: CustomRootComponentConfig<DefaultComponentProps, InternalFieldsBackgroundProps> = {
  label: 'Default Root',
  rootConfiguration: true,
  fields: {},
  internalFields: {
    extend: {
      $appearance: {
        design: {
          filterBlur: {
            type: 'number',
            label: 'Image Blur',
            min: 0,
            description: 'Apply a blur effect to the background, higher values create a stronger blur.',
            default: 25,
            visible(data) {
              return data.$appearance?.design?.useImage === true;
            },
          },
          useAdvancedFilters: {
            type: 'switch',
            label: 'Enable Image Filters',
            description:
              'Turn on to adjust the background image with advanced filters like brightness, contrast, saturation, and grayscale.',
            default: false,
            visible(data) {
              return data.$appearance?.design?.useImage === true;
            },
          },
          filterBrightness: {
            type: 'number',
            label: 'Image Brightness',
            description: 'Increase or decrease the brightness of the background image.',
            default: 1,
            min: 0,
            max: 3,
            step: 0.05,
            visible(data) {
              return data.$appearance?.design?.useAdvancedFilters === true && data.$appearance?.design?.useImage === true;
            },
          },
          filterContrast: {
            type: 'number',
            label: 'Image Contrast',
            description: 'Adjust the contrast of the background image for more or less distinction.',
            default: 1,
            min: 0,
            max: 3,
            step: 0.05,
            visible(data) {
              return data.$appearance?.design?.useAdvancedFilters === true && data.$appearance?.design?.useImage === true;
            },
          },
          filterSaturate: {
            type: 'number',
            label: 'Image Saturation',
            description: 'Change the intensity of colors in the background image.',
            default: 1,
            min: 0,
            max: 3,
            step: 0.05,
            visible(data) {
              return data.$appearance?.design?.useAdvancedFilters === true && data.$appearance?.design?.useImage === true;
            },
          },
          filterGrayscale: {
            type: 'number',
            label: 'Image Grayscale',
            description: 'Convert the background image to grayscale (black & white).',
            default: 0,
            min: 0,
            max: 1,
            step: 0.05,
            visible(data) {
              return data.$appearance?.design?.useAdvancedFilters === true && data.$appearance?.design?.useImage === true;
            },
          },
        },
        spacing: {
          type: 'object',
          section: {
            expanded: false,
          },
          label: 'Spacing',
          description: 'Spacing settings for the page',
          objectFields: {
            padding: {
              type: 'unit',
              label: 'Padding',
              description: 'Padding inside the container around the content area',
              default: '0rem',
              supportsAllCorners: true,
            },
            margin: {
              type: 'unit',
              label: 'Margin',
              description: 'Margin outside the container',
              default: '0rem',
              supportsAllCorners: true,
            },
          },
        },
      },
    },
    omit: {
      $appearance: {
        design: {
          useImage: true,
          backgroundImage: true,
        },
      },
    },
    defaults: {
      $appearance: {
        design: {
          useImage: true,
          backgroundImage: defaultBackground,
          backgroundImageBlendMode: 'multiply',
        },
      },
    },
  },
  styles(props) {
    // Note: CSS variables and internal styles are now generated by generateCssForInternalProps
    // This function only provides root-specific CSS structure and CSS reset
    // CSS variables are included via the helper in createRootComponent
    // Props parameter is required by type signature but values are generated by helper

    const filterParts: string[] = [];
    if (props.$appearance?.design?.filterBlur !== undefined) {
      filterParts.push(`blur(${props.$appearance?.design?.filterBlur}px)`);
    }
    if (props.$appearance?.design?.useAdvancedFilters) {
      if (props.$appearance?.design?.filterBrightness !== undefined) {
        filterParts.push(`brightness(${props.$appearance?.design?.filterBrightness})`);
      }
      if (props.$appearance?.design?.filterContrast !== undefined) {
        filterParts.push(`contrast(${props.$appearance?.design?.filterContrast})`);
      }
      if (props.$appearance?.design?.filterSaturate !== undefined) {
        filterParts.push(`saturate(${props.$appearance?.design?.filterSaturate})`);
      }
      if (props.$appearance?.design?.filterGrayscale !== undefined) {
        filterParts.push(`grayscale(${props.$appearance?.design?.filterGrayscale})`);
      }
    }

    // Build background-image: just the image (backgroundColor is handled separately via background-color)
    const blendMode = props.$appearance?.design?.backgroundImageBlendMode || 'normal';
    const hasImage = props.$appearance?.design?.useImage && props.$appearance?.design?.backgroundImage;
    const backgroundColor = props.$appearance?.design?.backgroundColor;
    const attachment = props.$appearance?.design?.backgroundAttachment || 'fixed';

    // Use CSS variable for background image (set by generateCssForInternalProps)
    const backgroundImage = hasImage ? 'var(--ha-background-image)' : 'none';

    // Apply blend-mode when we have both background color and image
    // background-color and background-image will blend together
    const backgroundBlendMode = backgroundColor && hasImage ? `background-blend-mode: ${blendMode};` : '';

    // Set position based on background-attachment:
    // - fixed: use position: fixed (stays in viewport)
    // - scroll/local: use position: absolute (scrolls with content)
    const pseudoElementPosition = attachment === 'fixed' ? 'fixed' : 'absolute';

    return `
      ${properties}
      :root {
        ${sharedCss}
      }
      /* Root Component Styles - Background attached to body */
      /* Use body::before pseudo-element so filters don't affect body content */
      body {
        position: relative;
        /* Ensure body content is above the background */
        isolation: isolate;
        /* Ensure body has minimum height for background coverage */
        min-height: 100vh;
      }


      .Root-content {
        margin: ${props.$appearance?.spacing?.margin};
        padding: ${props.$appearance?.spacing?.padding};
      }

      body::before {
        content: '';
        position: ${pseudoElementPosition};
        inset: 0;
        z-index: -1;
        pointer-events: none;
        background-color: var(--ha-background-color);
        background-position: var(--ha-background-position);
        background-repeat: var(--ha-background-repeat);
        background-size: var(--ha-background-size);
        background-image: ${backgroundImage};
        ${pseudoElementPosition === 'fixed' ? 'background-attachment: var(--ha-background-attachment);' : 'background-attachment: scroll;'}
        ${backgroundBlendMode}
        filter: ${filterParts.join(' ')};
      }

      /* ============================================
         CSS Reset & Normalization
         ============================================ */

      /* Box-sizing reset - makes width/height calculations intuitive */
      *,
      *::before,
      *::after {
        box-sizing: border-box;
      }

      /* Remove default margins on common elements */
      html,
      body,
      h1,
      h2,
      h3,
      h4,
      h5,
      h6,
      p,
      blockquote,
      pre,
      dl,
      dd,
      ol,
      ul,
      figure,
      hr,
      fieldset,
      legend {
        margin: 0;
        padding: 0;
      }

      html {
        /* Better font rendering on macOS/iOS */
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;

        /* Prevent iOS text size adjust after orientation change */
        -webkit-text-size-adjust: 100%;

        /* Enable smooth scrolling for anchor links */
        scroll-behavior: smooth;
      }

      /* Global Typography Styles */
      body {
        font-family: var(--ha-typography-font-family);
        font-size: var(--ha-typography-base-font-size);
        line-height: var(--ha-typography-line-height);
        letter-spacing: var(--ha-typography-letter-spacing);

        /* Better text rendering */
        text-rendering: optimizeLegibility;

        /* Minimum height for full viewport coverage */
        min-height: 100vh;
      }

      h1,
      h2,
      h3,
      h4,
      h5,
      h6 {
        font-family: var(--ha-typography-font-family);
        font-weight: var(--ha-typography-heading-weight);

        /* Better line-height for headings */
        line-height: 1.2;

        /* Prevent orphans in headings */
        text-wrap: balance;
      }

      /* Better paragraph spacing */
      p {
        line-height: var(--ha-typography-line-height);
      }

      /* Remove list styles by default (opt-in styling is more flexible) */
      ul,
      ol {
        list-style: none;
      }

      /* Better link defaults */
      a {
        text-decoration: none;
        color: inherit;
      }

      /* Make images easier to work with */
      img,
      picture,
      video,
      canvas,
      svg {
        display: block;
        max-width: 100%;
      }

      /* Remove built-in form element styling */
      input,
      button,
      textarea,
      select {
        background-color: transparent;
        border: none;
        outline: none;
      }

      /* Better focus styles for accessibility */
      :focus-visible {
        outline: 2px solid currentColor;
        outline-offset: 2px;
      }

      /* Remove spinners from number inputs */
      input[type='number']::-webkit-inner-spin-button,
      input[type='number']::-webkit-outer-spin-button {
        -webkit-appearance: none;
        margin: 0;
      }
      input[type='number'] {
        appearance: textfield;
        -moz-appearance: textfield;
      }

      /* Remove search input decorations */
      input[type='search']::-webkit-search-decoration,
      input[type='search']::-webkit-search-cancel-button,
      input[type='search']::-webkit-search-results-button,
      input[type='search']::-webkit-search-results-decoration {
        -webkit-appearance: none;
      }

      /* Better table defaults */
      table {
        border-collapse: collapse;
        border-spacing: 0;
      }

      /* Improve consistency of monospace fonts */
      pre,
      code,
      kbd,
      samp {
        font-family: ui-monospace, 'Cascadia Code', 'Source Code Pro', Menlo, Consolas, 'DejaVu Sans Mono', monospace;
        font-size: 1em;
      }

      /* Prevent text overflow */
      h1,
      h2,
      h3,
      h4,
      h5,
      h6,
      p {
        overflow-wrap: break-word;
      }

      /* Better hr element */
      hr {
        height: 0;
        border: 0;
        border-top: 1px solid currentColor;
        opacity: 0.25;
      }

      /* Improve media defaults */
      img,
      svg,
      video {
        height: auto;
      }

      /* Remove animations for users who prefer reduced motion */
      @media (prefers-reduced-motion: reduce) {
        *,
        *::before,
        *::after {
          animation-duration: 0.01ms !important;
          animation-iteration-count: 1 !important;
          transition-duration: 0.01ms !important;
          scroll-behavior: auto !important;
        }
      }
    `;
  },
  render: Render,
};

function Render(props: RenderProps<DefaultComponentProps>) {
  return (
    <>
      <Typography typography={props.$appearance?.typography} type='root' />
    </>
  );
}
