/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedMeIndexRouteImport } from './routes/_authenticated/me/index'
import { Route as AuthenticatedManagerIndexRouteImport } from './routes/_authenticated/manager/index'
import { Route as AuthenticatedAddonsIndexRouteImport } from './routes/_authenticated/addons/index'
import { Route as AuthenticatedMeSettingsIndexRouteImport } from './routes/_authenticated/me/settings/index'
import { Route as AuthenticatedMeLogoutIndexRouteImport } from './routes/_authenticated/me/logout/index'
import { Route as AuthenticatedMeHelpIndexRouteImport } from './routes/_authenticated/me/help/index'
import { Route as AuthenticatedMeDashboardsIndexRouteImport } from './routes/_authenticated/me/dashboards/index'
import { Route as AuthenticatedMeComponentsIndexRouteImport } from './routes/_authenticated/me/components/index'
import { Route as AuthenticatedDashboardNewIndexRouteImport } from './routes/_authenticated/dashboard/new/index'
import { Route as AuthenticatedMeDashboardPathEditRouteImport } from './routes/_authenticated/me/$dashboardPath/edit'
import { Route as AuthenticatedMeDashboardPathPagePathIndexRouteImport } from './routes/_authenticated/me/$dashboardPath/$pagePath/index'
import { Route as AuthenticatedDashboardEditDashboardPathIndexRouteImport } from './routes/_authenticated/dashboard/edit/$dashboardPath/index'
import { Route as AuthenticatedMeDashboardPathPagePathEditRouteImport } from './routes/_authenticated/me/$dashboardPath/$pagePath/edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeIndexRoute = AuthenticatedMeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMeRoute,
} as any)
const AuthenticatedManagerIndexRoute =
  AuthenticatedManagerIndexRouteImport.update({
    id: '/manager/',
    path: '/manager/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAddonsIndexRoute =
  AuthenticatedAddonsIndexRouteImport.update({
    id: '/addons/',
    path: '/addons/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeSettingsIndexRoute =
  AuthenticatedMeSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedMeRoute,
  } as any)
const AuthenticatedMeLogoutIndexRoute =
  AuthenticatedMeLogoutIndexRouteImport.update({
    id: '/logout/',
    path: '/logout/',
    getParentRoute: () => AuthenticatedMeRoute,
  } as any)
const AuthenticatedMeHelpIndexRoute =
  AuthenticatedMeHelpIndexRouteImport.update({
    id: '/help/',
    path: '/help/',
    getParentRoute: () => AuthenticatedMeRoute,
  } as any)
const AuthenticatedMeDashboardsIndexRoute =
  AuthenticatedMeDashboardsIndexRouteImport.update({
    id: '/dashboards/',
    path: '/dashboards/',
    getParentRoute: () => AuthenticatedMeRoute,
  } as any)
const AuthenticatedMeComponentsIndexRoute =
  AuthenticatedMeComponentsIndexRouteImport.update({
    id: '/components/',
    path: '/components/',
    getParentRoute: () => AuthenticatedMeRoute,
  } as any)
const AuthenticatedDashboardNewIndexRoute =
  AuthenticatedDashboardNewIndexRouteImport.update({
    id: '/dashboard/new/',
    path: '/dashboard/new/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeDashboardPathEditRoute =
  AuthenticatedMeDashboardPathEditRouteImport.update({
    id: '/$dashboardPath/edit',
    path: '/$dashboardPath/edit',
    getParentRoute: () => AuthenticatedMeRoute,
  } as any)
const AuthenticatedMeDashboardPathPagePathIndexRoute =
  AuthenticatedMeDashboardPathPagePathIndexRouteImport.update({
    id: '/$dashboardPath/$pagePath/',
    path: '/$dashboardPath/$pagePath/',
    getParentRoute: () => AuthenticatedMeRoute,
  } as any)
const AuthenticatedDashboardEditDashboardPathIndexRoute =
  AuthenticatedDashboardEditDashboardPathIndexRouteImport.update({
    id: '/dashboard/edit/$dashboardPath/',
    path: '/dashboard/edit/$dashboardPath/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeDashboardPathPagePathEditRoute =
  AuthenticatedMeDashboardPathPagePathEditRouteImport.update({
    id: '/$dashboardPath/$pagePath/edit',
    path: '/$dashboardPath/$pagePath/edit',
    getParentRoute: () => AuthenticatedMeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/me': typeof AuthenticatedMeRouteWithChildren
  '/addons': typeof AuthenticatedAddonsIndexRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
  '/me/': typeof AuthenticatedMeIndexRoute
  '/me/$dashboardPath/edit': typeof AuthenticatedMeDashboardPathEditRoute
  '/dashboard/new': typeof AuthenticatedDashboardNewIndexRoute
  '/me/components': typeof AuthenticatedMeComponentsIndexRoute
  '/me/dashboards': typeof AuthenticatedMeDashboardsIndexRoute
  '/me/help': typeof AuthenticatedMeHelpIndexRoute
  '/me/logout': typeof AuthenticatedMeLogoutIndexRoute
  '/me/settings': typeof AuthenticatedMeSettingsIndexRoute
  '/me/$dashboardPath/$pagePath/edit': typeof AuthenticatedMeDashboardPathPagePathEditRoute
  '/dashboard/edit/$dashboardPath': typeof AuthenticatedDashboardEditDashboardPathIndexRoute
  '/me/$dashboardPath/$pagePath': typeof AuthenticatedMeDashboardPathPagePathIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/addons': typeof AuthenticatedAddonsIndexRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
  '/me': typeof AuthenticatedMeIndexRoute
  '/me/$dashboardPath/edit': typeof AuthenticatedMeDashboardPathEditRoute
  '/dashboard/new': typeof AuthenticatedDashboardNewIndexRoute
  '/me/components': typeof AuthenticatedMeComponentsIndexRoute
  '/me/dashboards': typeof AuthenticatedMeDashboardsIndexRoute
  '/me/help': typeof AuthenticatedMeHelpIndexRoute
  '/me/logout': typeof AuthenticatedMeLogoutIndexRoute
  '/me/settings': typeof AuthenticatedMeSettingsIndexRoute
  '/me/$dashboardPath/$pagePath/edit': typeof AuthenticatedMeDashboardPathPagePathEditRoute
  '/dashboard/edit/$dashboardPath': typeof AuthenticatedDashboardEditDashboardPathIndexRoute
  '/me/$dashboardPath/$pagePath': typeof AuthenticatedMeDashboardPathPagePathIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/me': typeof AuthenticatedMeRouteWithChildren
  '/_authenticated/addons/': typeof AuthenticatedAddonsIndexRoute
  '/_authenticated/manager/': typeof AuthenticatedManagerIndexRoute
  '/_authenticated/me/': typeof AuthenticatedMeIndexRoute
  '/_authenticated/me/$dashboardPath/edit': typeof AuthenticatedMeDashboardPathEditRoute
  '/_authenticated/dashboard/new/': typeof AuthenticatedDashboardNewIndexRoute
  '/_authenticated/me/components/': typeof AuthenticatedMeComponentsIndexRoute
  '/_authenticated/me/dashboards/': typeof AuthenticatedMeDashboardsIndexRoute
  '/_authenticated/me/help/': typeof AuthenticatedMeHelpIndexRoute
  '/_authenticated/me/logout/': typeof AuthenticatedMeLogoutIndexRoute
  '/_authenticated/me/settings/': typeof AuthenticatedMeSettingsIndexRoute
  '/_authenticated/me/$dashboardPath/$pagePath/edit': typeof AuthenticatedMeDashboardPathPagePathEditRoute
  '/_authenticated/dashboard/edit/$dashboardPath/': typeof AuthenticatedDashboardEditDashboardPathIndexRoute
  '/_authenticated/me/$dashboardPath/$pagePath/': typeof AuthenticatedMeDashboardPathPagePathIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/me'
    | '/addons'
    | '/manager'
    | '/me/'
    | '/me/$dashboardPath/edit'
    | '/dashboard/new'
    | '/me/components'
    | '/me/dashboards'
    | '/me/help'
    | '/me/logout'
    | '/me/settings'
    | '/me/$dashboardPath/$pagePath/edit'
    | '/dashboard/edit/$dashboardPath'
    | '/me/$dashboardPath/$pagePath'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/addons'
    | '/manager'
    | '/me'
    | '/me/$dashboardPath/edit'
    | '/dashboard/new'
    | '/me/components'
    | '/me/dashboards'
    | '/me/help'
    | '/me/logout'
    | '/me/settings'
    | '/me/$dashboardPath/$pagePath/edit'
    | '/dashboard/edit/$dashboardPath'
    | '/me/$dashboardPath/$pagePath'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/me'
    | '/_authenticated/addons/'
    | '/_authenticated/manager/'
    | '/_authenticated/me/'
    | '/_authenticated/me/$dashboardPath/edit'
    | '/_authenticated/dashboard/new/'
    | '/_authenticated/me/components/'
    | '/_authenticated/me/dashboards/'
    | '/_authenticated/me/help/'
    | '/_authenticated/me/logout/'
    | '/_authenticated/me/settings/'
    | '/_authenticated/me/$dashboardPath/$pagePath/edit'
    | '/_authenticated/dashboard/edit/$dashboardPath/'
    | '/_authenticated/me/$dashboardPath/$pagePath/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/addons/': {
      id: '/_authenticated/addons/'
      path: '/addons'
      fullPath: '/addons'
      preLoaderRoute: typeof AuthenticatedAddonsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/': {
      id: '/_authenticated/manager/'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/': {
      id: '/_authenticated/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof AuthenticatedMeIndexRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/me/$dashboardPath/edit': {
      id: '/_authenticated/me/$dashboardPath/edit'
      path: '/$dashboardPath/edit'
      fullPath: '/me/$dashboardPath/edit'
      preLoaderRoute: typeof AuthenticatedMeDashboardPathEditRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/dashboard/new/': {
      id: '/_authenticated/dashboard/new/'
      path: '/dashboard/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof AuthenticatedDashboardNewIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/components/': {
      id: '/_authenticated/me/components/'
      path: '/components'
      fullPath: '/me/components'
      preLoaderRoute: typeof AuthenticatedMeComponentsIndexRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/me/dashboards/': {
      id: '/_authenticated/me/dashboards/'
      path: '/dashboards'
      fullPath: '/me/dashboards'
      preLoaderRoute: typeof AuthenticatedMeDashboardsIndexRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/me/help/': {
      id: '/_authenticated/me/help/'
      path: '/help'
      fullPath: '/me/help'
      preLoaderRoute: typeof AuthenticatedMeHelpIndexRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/me/logout/': {
      id: '/_authenticated/me/logout/'
      path: '/logout'
      fullPath: '/me/logout'
      preLoaderRoute: typeof AuthenticatedMeLogoutIndexRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/me/settings/': {
      id: '/_authenticated/me/settings/'
      path: '/settings'
      fullPath: '/me/settings'
      preLoaderRoute: typeof AuthenticatedMeSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/me/$dashboardPath/$pagePath/edit': {
      id: '/_authenticated/me/$dashboardPath/$pagePath/edit'
      path: '/$dashboardPath/$pagePath/edit'
      fullPath: '/me/$dashboardPath/$pagePath/edit'
      preLoaderRoute: typeof AuthenticatedMeDashboardPathPagePathEditRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/dashboard/edit/$dashboardPath/': {
      id: '/_authenticated/dashboard/edit/$dashboardPath/'
      path: '/dashboard/edit/$dashboardPath'
      fullPath: '/dashboard/edit/$dashboardPath'
      preLoaderRoute: typeof AuthenticatedDashboardEditDashboardPathIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/$dashboardPath/$pagePath/': {
      id: '/_authenticated/me/$dashboardPath/$pagePath/'
      path: '/$dashboardPath/$pagePath'
      fullPath: '/me/$dashboardPath/$pagePath'
      preLoaderRoute: typeof AuthenticatedMeDashboardPathPagePathIndexRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
  }
}

interface AuthenticatedMeRouteChildren {
  AuthenticatedMeIndexRoute: typeof AuthenticatedMeIndexRoute
  AuthenticatedMeDashboardPathEditRoute: typeof AuthenticatedMeDashboardPathEditRoute
  AuthenticatedMeComponentsIndexRoute: typeof AuthenticatedMeComponentsIndexRoute
  AuthenticatedMeDashboardsIndexRoute: typeof AuthenticatedMeDashboardsIndexRoute
  AuthenticatedMeHelpIndexRoute: typeof AuthenticatedMeHelpIndexRoute
  AuthenticatedMeLogoutIndexRoute: typeof AuthenticatedMeLogoutIndexRoute
  AuthenticatedMeSettingsIndexRoute: typeof AuthenticatedMeSettingsIndexRoute
  AuthenticatedMeDashboardPathPagePathEditRoute: typeof AuthenticatedMeDashboardPathPagePathEditRoute
  AuthenticatedMeDashboardPathPagePathIndexRoute: typeof AuthenticatedMeDashboardPathPagePathIndexRoute
}

const AuthenticatedMeRouteChildren: AuthenticatedMeRouteChildren = {
  AuthenticatedMeIndexRoute: AuthenticatedMeIndexRoute,
  AuthenticatedMeDashboardPathEditRoute: AuthenticatedMeDashboardPathEditRoute,
  AuthenticatedMeComponentsIndexRoute: AuthenticatedMeComponentsIndexRoute,
  AuthenticatedMeDashboardsIndexRoute: AuthenticatedMeDashboardsIndexRoute,
  AuthenticatedMeHelpIndexRoute: AuthenticatedMeHelpIndexRoute,
  AuthenticatedMeLogoutIndexRoute: AuthenticatedMeLogoutIndexRoute,
  AuthenticatedMeSettingsIndexRoute: AuthenticatedMeSettingsIndexRoute,
  AuthenticatedMeDashboardPathPagePathEditRoute:
    AuthenticatedMeDashboardPathPagePathEditRoute,
  AuthenticatedMeDashboardPathPagePathIndexRoute:
    AuthenticatedMeDashboardPathPagePathIndexRoute,
}

const AuthenticatedMeRouteWithChildren = AuthenticatedMeRoute._addFileChildren(
  AuthenticatedMeRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedMeRoute: typeof AuthenticatedMeRouteWithChildren
  AuthenticatedAddonsIndexRoute: typeof AuthenticatedAddonsIndexRoute
  AuthenticatedManagerIndexRoute: typeof AuthenticatedManagerIndexRoute
  AuthenticatedDashboardNewIndexRoute: typeof AuthenticatedDashboardNewIndexRoute
  AuthenticatedDashboardEditDashboardPathIndexRoute: typeof AuthenticatedDashboardEditDashboardPathIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMeRoute: AuthenticatedMeRouteWithChildren,
  AuthenticatedAddonsIndexRoute: AuthenticatedAddonsIndexRoute,
  AuthenticatedManagerIndexRoute: AuthenticatedManagerIndexRoute,
  AuthenticatedDashboardNewIndexRoute: AuthenticatedDashboardNewIndexRoute,
  AuthenticatedDashboardEditDashboardPathIndexRoute:
    AuthenticatedDashboardEditDashboardPathIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
