/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedEditorIndexImport } from './routes/_authenticated/editor/index'
import { Route as AuthenticatedPreviewDashboardPathImport } from './routes/_authenticated/preview/$dashboardPath'
import { Route as AuthenticatedEditorDashboardPathImport } from './routes/_authenticated/editor/$dashboardPath'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedEditorIndexRoute = AuthenticatedEditorIndexImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedPreviewDashboardPathRoute =
  AuthenticatedPreviewDashboardPathImport.update({
    id: '/preview/$dashboardPath',
    path: '/preview/$dashboardPath',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedEditorDashboardPathRoute =
  AuthenticatedEditorDashboardPathImport.update({
    id: '/editor/$dashboardPath',
    path: '/editor/$dashboardPath',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/editor/$dashboardPath': {
      id: '/_authenticated/editor/$dashboardPath'
      path: '/editor/$dashboardPath'
      fullPath: '/editor/$dashboardPath'
      preLoaderRoute: typeof AuthenticatedEditorDashboardPathImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/preview/$dashboardPath': {
      id: '/_authenticated/preview/$dashboardPath'
      path: '/preview/$dashboardPath'
      fullPath: '/preview/$dashboardPath'
      preLoaderRoute: typeof AuthenticatedPreviewDashboardPathImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/editor/': {
      id: '/_authenticated/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AuthenticatedEditorIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedEditorDashboardPathRoute: typeof AuthenticatedEditorDashboardPathRoute
  AuthenticatedPreviewDashboardPathRoute: typeof AuthenticatedPreviewDashboardPathRoute
  AuthenticatedEditorIndexRoute: typeof AuthenticatedEditorIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEditorDashboardPathRoute: AuthenticatedEditorDashboardPathRoute,
  AuthenticatedPreviewDashboardPathRoute:
    AuthenticatedPreviewDashboardPathRoute,
  AuthenticatedEditorIndexRoute: AuthenticatedEditorIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/editor/$dashboardPath': typeof AuthenticatedEditorDashboardPathRoute
  '/preview/$dashboardPath': typeof AuthenticatedPreviewDashboardPathRoute
  '/editor': typeof AuthenticatedEditorIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/editor/$dashboardPath': typeof AuthenticatedEditorDashboardPathRoute
  '/preview/$dashboardPath': typeof AuthenticatedPreviewDashboardPathRoute
  '/editor': typeof AuthenticatedEditorIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/editor/$dashboardPath': typeof AuthenticatedEditorDashboardPathRoute
  '/_authenticated/preview/$dashboardPath': typeof AuthenticatedPreviewDashboardPathRoute
  '/_authenticated/editor/': typeof AuthenticatedEditorIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/editor/$dashboardPath'
    | '/preview/$dashboardPath'
    | '/editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/editor/$dashboardPath'
    | '/preview/$dashboardPath'
    | '/editor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/editor/$dashboardPath'
    | '/_authenticated/preview/$dashboardPath'
    | '/_authenticated/editor/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/editor/$dashboardPath",
        "/_authenticated/preview/$dashboardPath",
        "/_authenticated/editor/"
      ]
    },
    "/_authenticated/editor/$dashboardPath": {
      "filePath": "_authenticated/editor/$dashboardPath.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/preview/$dashboardPath": {
      "filePath": "_authenticated/preview/$dashboardPath.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/editor/": {
      "filePath": "_authenticated/editor/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
